Repository wp-cli/cache-command, pull requests merged in 2019-04, with the labels that each got.

#52 Move PHP 5.4 tests from `WP_VERSION` `latest` to `5.1`
  .travis.yml
Labels: scope:distribution

#53 Prefix variables in global namespace
  cache-command.php
Labels: command:cache

#56 Enhancement: Add PHP 7.3 to Travis CI build matrix
  .travis.yml
Labels: scope:testing

#57 Use prefix `wpcli_` instead of `wp_cli_`
  cache-command.php
Labels: scope:testing

#58 Update to latest tests package
  composer.json
Labels: scope:testing
